### ISSUE TITLE
circular import error with pucudadecon

### ISSUE THREAD

**Issue by OptoManishK** [tlambert03/pycudadecon#32]
Hi,
I am just getting started with this package to do deconvolution.

For the very first line of the example code I ran into this error:
ImportError: cannot import name 'decon' from partially initialized module 'pycudadecon' (most likely due to a circular import)

I am on a windows 10 PC and used following to install pycudadecon in a new environment:
```
conda create --name test python
conda activate test
conda install -c conda-forge cudadecon cudatoolkit=11.2
```
Any pointers to what might be going wrong?

**Comment by tlambert03** [comment]
hmm.. that seems like something that would be an error on my end, but I can't reproduce it. I just ran the code you listed above (but I changed `cudadecon` to `pycudadecon`, I assume that was a typo?) and it worked for me, when I tried `from pycudadecon import decon`...  can you perhaps provide a bit more info on how you're importing it?

**Comment by OptoManishK** [comment]
oops ..... i copied that typo from Documentation section of readme.md file 
![image](https://user-images.githubusercontent.com/31775684/125016700-62c78c80-e037-11eb-9e66-80215261be77.png)

I corrected it and everything runs without errors. Thank you and please update that typo.

I'm excited to try this.

**Comment by tlambert03** [comment]
Oops!  Thanks!

**Comment by tlambert03** [comment]
updated thanks... Also, just in case you missed it, that "Documentation" word there is a link to the documentation: https://www.talleylambert.com/pycudadecon/index.html ... (not the complete documentation section :) )
